### ISSUE TITLE
Le nouveau menu n'est pas utilisable à la souris

### ISSUE THREAD

**Issue by AntoineJ** [erasme/museotouch#4]

**Comment by florian-chassaing** [comment]
Si normalement avec un clic droit !

**Comment by AntoineJ** [comment]
Autant pour moi, j'avais pas vu!

Par contre il y a toujours une erreur sur windows lorsque je clic sur le bouton fermer : 

![capture](https://cloud.githubusercontent.com/assets/234059/9717794/d7f570ec-5575-11e5-8233-6f185d3c8d07.PNG)

**Comment by florian-chassaing** [comment]
Bizarre, ici ça fonctionne. 
Ca le fait à chaque fois ?
Sous Windows 8.1 ? 10 ?
Peux-tu reproduire la totalité de la trace ?

**Comment by AntoineJ** [comment]
Hello, 

Je pensai à un moment que ça venait de la configuration de Kivy qui acceptait les contacts de la souris et de wm_touch, mais ca n'a rien changé. J'ai même désactivé wm_touch et la souris pour laisser uniquement le tuio du cadre tactile mais ca ne change pas.

Le problème est "invisible" puisqu'avec la dernière modif du main.py, museotouch se ferme totalement lors du crash (plus de trace visible) et est donc automatiquement relancé. On voit donc un écran noir pendant 1 sec.

**Comment by florian-chassaing** [comment]
Salut,

Je viens de tester sur un Lenovo All-in-One qui tourne sous Windows 8.1 64 bits et je ne parviens pas à reproduire le bug (lancement avec et sans kiosk.bat). Idem sous Ubuntu. La version de Kivy utilisée était la même que celle installée sur la table.
Pour voir la trace tu peux peut-être lancer educatouch sans kiosk.bat à partir d'une ligne de commande kivy-2.7.bat ?

**Comment by AntoineJ** [comment]
Avec un clic droit, et sans écran tactile, j'ai le même problème sur ubuntu et kivy 1.9.0. La trace est identique à celle indiquée au début de la conversation : 
![capture du 2015-10-28 17 27 57](https://cloud.githubusercontent.com/assets/234059/10795267/46cf8e8a-7d99-11e5-9d66-0b9b7ea112c2.png)

**Comment by AntoineJ** [comment]
A priori, problème corrigé avec le dernier commit 

https://github.com/erasme/museotouch/commit/b39fe1c293dccd2c9f3adaf0265c730221eda41f
